[package]
name = "minicoap"
version = "0.1.0"
edition = "2024"

[dependencies]
num_enum = { version = "0.7.4", default-features = false }

defmt = { version = "1.0.1", optional = true }

[features]
defmt = ["dep:defmt"]
